export const ADD_TODO = "ADD_TODO"
export const TOGGLE_TODO = "TOGGLE_TODO"
export const SET_FILTER = "SET_FILTER"
export const SET_TODO_TEXT = "SET_TODO_TEXT"
export const FETTH_TODOS_REQUEST = 'FETTH_TODOS_REQUEST'
export const FETTH_TODOS_SUCCESS = 'FETTH_TODOS_SUCCESS'
export const FETTH_TODOS_FAILURE = 'FETTH_TODOS_FAILURE'
